const String DATABASE_NAME = 'git_repository_info_db';

const String REPOSITORY_TABLE_NAME = 'repository';
const String REPOSITORY_COLUMN_REPOSITORYID = 'repositoryID';
const String REPOSITORY_COLUMN_NAME = 'name';
const String REPOSITORY_COLUMN_DESCRIPTION = 'description';
const String REPOSITORY_COLUMN_CREATE_AT = 'created_at';
const String REPOSITORY_COLUMN_LANGUAGE = 'language';
const String REPOSITORY_COLUMN_STARGAZERS_COUNT = 'stargazers_count';

const String CREATE_REPOSITORY_TABLE_SCRIPT =
    ''' CREATE TABLE $REPOSITORY_TABLE_NAME 
  (
    $REPOSITORY_COLUMN_REPOSITORYID INTEGER PRIMARY KEY,
    $REPOSITORY_COLUMN_NAME TEXT,
    $REPOSITORY_COLUMN_DESCRIPTION TEXT,
    $REPOSITORY_COLUMN_CREATE_AT TEXT,
    $REPOSITORY_COLUMN_LANGUAGE TEXT,
    $REPOSITORY_COLUMN_STARGAZERS_COUNT INTEGER
  ) ''';
